### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by foss-what-else** [karlicoss/rexport#1]
When I run the script I get a syntax error

```
pi@raspberrypi:~/projects/rexport$ python rexport.py --secrets reddit_secrets.py
  File "rexport.py", line 14
    profile: Dict
           ^
SyntaxError: invalid syntax
```

**Comment by karlicoss** [comment]
Hey, sorry for late reply. I think it's caused by Python version, you must be using something < 3.6? Any chance you could run it via python3.6 or higher instead?

**Comment by karlicoss** [comment]
Closing since it's stale, but feel free to comment & reopen

**Comment by foss-what-else** [comment]
Works with Python < 3.6. Thanks!
